### ISSUE TITLE
SQL query support

### ISSUE THREAD

**Issue by entertainment-inteligence** [mohaseeb/beam-nuggets#17]
I noticed SQL query support is on your backlog. I would find this an extremely useful feature. For example, I could then run a Batch pipeline to only load new DB entries rather than full tables each time. Happy to attempt a contribution with some guidance as new to Python.

**Comment by mohaseeb** [comment]
Hi @entertainment-inteligence, please feel free to make a proposal that we can refine together (if needed). Otherwise I can work on it later next week.

Some thoughts/suggestions for the might-be-needed changes:
- Updating the [logic for loading](https://github.com/mohaseeb/beamnuggets/blob/master/beam_nuggets/io/relational_db_api.py#L339) the entries (or rows), possibly to use something like [this](https://docs.sqlalchemy.org/en/latest/orm/tutorial.html#using-textual-sql) (3rd paragraph) to incorporate the sql query.
- [The logic](https://github.com/mohaseeb/beam-nuggets/blob/master/beam_nuggets/io/relational_db_api.py#L360) for mapping the loaded entries to dictionaries assumes all the table columns are included in the returned entries. This isn't necessarily the case for user queries; a user query can select a subset from all the columns. So this part needs to be updated. It might be possible to infer the returned columns from (session.query) or from the loaded db entries (I don't know for sure, but worth checking). Otherwise we could let the user pass the mapping logic (this has benefits beyond allowing a subset of the columns; the user could have an arbitrary mapping of the returned entries).
- The `relational_db.Read` API can be extended to something like:
```python
relational_db.Read(
   source_config=source_config,
   table_name=table_name,
   query='select name, age from student',
   row_mapper=lambda entry: {'name': entry.name, 'age': entry.age}
)
```
You check beam's [jdbcio](https://beam.apache.org/releases/javadoc/2.1.0/org/apache/beam/sdk/io/jdbc/JdbcIO.html) for inspiration.

**Comment by mohaseeb** [comment]
This has been implemented by this PR https://github.com/mohaseeb/beam-nuggets/pull/18
